name: Publish 

on: 
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    env: 
      GITHUB_PACKAGES_AUTH_TOKEN: ${{secrets.GH_TOKEN}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://npm.pkg.github.com/"
      
      - name: Configure git user
        run: |
        git config --local user.name "Github Actions"
        git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install dependencies
        run: npm install

      - name: Publish
        run: |
          lerna publish --yes
      